#!/bin/bash


GT=""
# HOST=localhost
echo `gettext -d timecl "Enter the host:"`
read HOST
if [ "`grep -c 46574 /etc/services`" == 1 ]
then
	PORT=46574
	# echo "Port 46574 ok"
else
	echo `gettext -d timecl "OPERATING PORT MAY BE OCCUPIED OR NOT INSTALLED. CHECK THE /ETC/SERVICES"`
	exit 2
fi

# --------------------------------------Checking the connection

if echo $ZONE | nc $HOST $PORT 2> /dev/null
then
	echo `gettext -d timecl "Server OK"`
else
	echo `gettext -d timecl "Server is not available at the host specified. Halting."`
	exit 2
fi

# --------------------------------------The text UI part

# echo `gettext -d timecl "Application stared. Press Ctrl+c to exit."`
# while [ True ]
# do
# 	echo `gettext -d timecl "Enter the zone:"`
# 	read Z
# 	echo `gettext -d timecl "Enter the city:"`
# 	read C
# 	ZONE="$Z/$C"
# 	if OUTP=$(echo $ZONE | nc $HOST $PORT)
# 	then
# 		echo $OUTP
# 	# else
# 	# 	echo "Server is not available at the host specified. Halting."
# 	# 	exit 2
# 	fi
# done

# --------------------------------------The graphical UI part

while [ True ] 
do
	if OUTP=$(zenity --entry --title "`gettext -d timecl "Enter the zone"`" \
			 --text "`gettext -d timecl "The zone"`" --entry-text "Europe/Paris" | nc $HOST $PORT)
	then
		echo $OUTP
		if zenity --question --text="$OUTP \r\n`gettext -d timecl "Do you want to fetch the time again?"`"
		then
			echo ""
		else 
			break
		fi
	# else
	# 	echo `gettext -d timecl "Server is not available at the host specified. Halting."`
	# 	exit 2
	fi
done