#!/bin/bash


GT=""
# HOST=localhost
echo `gettext -d timecl "Enter the host:"`
read HOST
if [ "`grep -c 46574 /etc/services`" == 1 ]
then
	PORT=46574
	# echo "Port 46574 ok"
else
	echo `gettext -d timecl "OPERATING PORT MAY BE OCCUPIED OR NOT INSTALLED. CHECK THE /ETC/SERVICES"`
	exit 2
fi

# --------------------------------------Checking the connection

if echo $ZONE | nc $HOST $PORT 2> /dev/null
then
	echo `gettext -d timecl "Server OK"`
else
	echo `gettext -d timecl "Server is not available at the host specified. Halting."`
	exit 2
fi

# --------------------------------------The text UI part


if $DISPLAY 2> /dev/null 
then
	echo `gettext -d timecl "Application stared. Press Ctrl+c to exit."`
	while [ True ]
	do
		echo `gettext -d timecl "Enter the zone:"`
		read Z
		echo `gettext -d timecl "Enter the city:"`
		read C
		ZONE="$Z/$C"
		# if OUTP=$(echo $ZONE | nc $HOST $PORT)
		# then
		# 	echo $OUTP
		if OUTP=$(echo $ZONE | nc $HOST $PORT)
		then
			if [ $OUTP = 0 2> /dev/null ]
			then
				TEXT=$(echo `gettext -d timecl "No such city or zone in the system. Refer to date TZ specs."`)
			else
				TEXT=$(echo `gettext -d timecl "The current time in this time zone is: "`)
				TEXT+=$(echo "	`gettext -d date "$OUTP"`")     # does not work :c
			fi
			echo $TEXT
		# else
		# 	echo "Server is not available at the host specified. Halting."
		# 	exit 2
		fi
	done

	# --------------------------------------The graphical UI part
else
	while [ True ] 
	do
		if OUTP=$(zenity --entry --title "`gettext -d timecl "Enter the zone"`" \
				 --text "`gettext -d timecl "Zone/City:"`" --entry-text "Europe/Paris" | nc $HOST $PORT)
		then
			if [ $OUTP = 0 2> /dev/null ]
			then
				TEXT=$(echo `gettext -d timecl "No such city or zone in the system. Refer to date TZ specs."`)
			else
				TEXT=$(echo `gettext -d timecl "The current time in this time zone is: "`)
				TEXT+=$(echo "\r\n`gettext -d date "$OUTP"`")     # does not work :c
			fi
			echo $TEXT
			if zenity --question --text="$TEXT \r\n`gettext -d timecl "Do you want to fetch the time again?"`"
			then
				echo ""
			else 
				break
			fi
		# else
		# 	echo `gettext -d timecl "Server is not available at the host specified. Halting."`
		# 	exit 2
		fi
	done
fi